import type { Metadata } from "next";
import "./globals.css";
import "./fonts.css";
import { WagmiProvider } from "wagmi";
import { config } from "@/utils/chainConfig";

export const metadata: Metadata = {
  title: "Midway",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#FEFBEC] antialiased`}
      >
        <WagmiProvider config={config}>
          {children}
        </WagmiProvider>
      </body>
    </html>
  );
}
