import type { Metadata } from "next";
import "./globals.css";
import "./fonts.css";
import Web3Provider from "@/components/Web3Provider";

export const metadata: Metadata = {
  title: "Midway",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#FEFBEC] antialiased`}
      >
        <Web3Provider>
          {children}
        </Web3Provider>
      </body>
    </html>
  );
}
